package tianchengDataMining

object TianChengConstant {
  // 原始数据操作字段
  val OPERATION_UID = 0
  val OPERATION_DAY = 1
  val OPERATION_MODE = 2
  val OPERATION_SUCCESS = 3
  val OPERATION_TIME = 4
  val OPERATION_OS = 5
  val OPERATION_VERSION = 6
  val OPERATION_DEVICE1 = 7
  val OPERATION_DEVICE2 = 8
  val OPERATION_DEVICE_CODE1 = 9
  val OPERATION_DEVICE_CODE2 = 10
  val OPERATION_DEVICE_CODE3 = 11
  val OPERATION_MAC1 = 12
  val OPERATION_MAC2 = 13
  val OPERATION_IP1 = 14
  val OPERATION_IP2 = 15
  val OPERATION_WIFI = 16
  val OPERATION_GEO_CODE = 17
  val OPERATION_IP1_SUB = 18
  val OPERATION_IP2_SUB = 19

  // 原始数据交易字段
  val TRANSACTION_UID = 0
  val TRANSACTION_CHANNEL = 1
  val TRANSACTION_DAY = 2
  val TRANSACTION_TIME = 3
  val TRANSACTION_TRANS_AMT = 4
  val TRANSACTION_AMT_SRC1 = 5
  val TRANSACTION_MERCHANT = 6
  val TRANSACTION_CODE1 = 7
  val TRANSACTION_CODE2 = 8
  val TRANSACTION_TRANS_TYPE1 = 9
  val TRANSACTION_ACC_ID1 = 10
  val TRANSACTION_DEVICE_CODE1 = 11
  val TRANSACTION_DEVICE_CODE2 = 12
  val TRANSACTION_DEVICE_CODE3 = 13
  val TRANSACTION_DEVICE1 = 14
  val TRANSACTION_DEVICE2 = 15
  val TRANSACTION_MAC1 = 16
  val TRANSACTION_IP1 = 17
  val TRANSACTION_BAL = 18
  val TRANSACTION_AMT_SRC2 = 19
  val TRANSACTION_ACC_ID2 = 20
  val TRANSACTION_ACC_ID3 = 21
  val TRANSACTION_GEO_CODE = 22
  val TRANSACTION_TRANS_TYPE2 = 23
  val TRANSACTION_MARKET_CODE = 24
  val TRANSACTION_MARKET_TYPE = 25
  val TRANSACTION_IP1_SUB = 26

  // 精简数据操作字段
  val OP_UID = 0
  val OP_DAY = 1
  val OP_MODE = 2
  val OP_TIME = 3

  // 精简数据交易字段
  val TRANS_UID = 0
  val TRANS_CHANNEL = 1
  val TRANS_DAY = 2
  val TRANS_AMT = 3
  val TRANS_TIME = 4
  val TRANS_TYPE1 = 5
  val TRANS_TYPE2 = 6

}
